// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5hI-HjtIe_U_nnHHxQqNYTeBGFO6uU6c',
    appId: '1:837011596382:web:926e70f8819296da6c40cf',
    messagingSenderId: '837011596382',
    projectId: 'peaper-dd503',
    authDomain: 'peaper-dd503.firebaseapp.com',
    storageBucket: 'peaper-dd503.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHu3Xm5lizb3Nmi9r3KT_puOHetYBwu4U',
    appId: '1:837011596382:android:e4e9ce5d0e489cea6c40cf',
    messagingSenderId: '837011596382',
    projectId: 'peaper-dd503',
    storageBucket: 'peaper-dd503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzbkmlinRY9oHvsdpKJ_JRukzEojE5M7c',
    appId: '1:837011596382:ios:bafe217e8d11d09b6c40cf',
    messagingSenderId: '837011596382',
    projectId: 'peaper-dd503',
    storageBucket: 'peaper-dd503.appspot.com',
    iosClientId: '837011596382-1843qsencjvlglqslkh9gdmjsltkus2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzbkmlinRY9oHvsdpKJ_JRukzEojE5M7c',
    appId: '1:837011596382:ios:bafe217e8d11d09b6c40cf',
    messagingSenderId: '837011596382',
    projectId: 'peaper-dd503',
    storageBucket: 'peaper-dd503.appspot.com',
    iosClientId: '837011596382-1843qsencjvlglqslkh9gdmjsltkus2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5hI-HjtIe_U_nnHHxQqNYTeBGFO6uU6c',
    appId: '1:837011596382:web:f020730420058b9d6c40cf',
    messagingSenderId: '837011596382',
    projectId: 'peaper-dd503',
    authDomain: 'peaper-dd503.firebaseapp.com',
    storageBucket: 'peaper-dd503.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC5hI-HjtIe_U_nnHHxQqNYTeBGFO6uU6c',
    appId: '1:837011596382:web:7aec5eec10ef04946c40cf',
    messagingSenderId: '837011596382',
    projectId: 'peaper-dd503',
    authDomain: 'peaper-dd503.firebaseapp.com',
    storageBucket: 'peaper-dd503.appspot.com',
  );
}
